### ISSUE TITLE
error in utils/process.py in latest master

### ISSUE THREAD

**Issue by mzweilin** [cuckoobox/cuckoo#591] opened 2015-06-29 20:09 UTC
$ ./utils/process.py -p 5 auto

```
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/xuweilin/coder/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/home/xuweilin/coder/cuckoo/utils/../modules/reporting/mongodb.py", line 187, in run
    for index, call in enumerate(process["calls"]):
  File "/home/xuweilin/coder/cuckoo/utils/../modules/processing/behavior.py", line 124, in next
    if not self.wait_for_lastcall():
  File "/home/xuweilin/coder/cuckoo/utils/../modules/processing/behavior.py", line 113, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/home/xuweilin/coder/cuckoo/utils/../lib/cuckoo/common/netlog.py", line 266, in read_next_message
    data = self.handler.read(4)
  File "/home/xuweilin/coder/cuckoo/utils/../modules/processing/behavior.py", line 76, in read
    buf = self.fd.read(length)
ValueError: I/O operation on closed file
```

**Comment by botherder** [comment] 2015-06-30 01:03
Thanks for reporting.

**Comment by SpoonBoy** [comment] 2015-06-30 12:28
confirm, it does throw an error when using the process.py in auto mode.
The same issue happen when trying to use the  -r  option also.
(but anyway, the report seems to be generated and properly displayed in django)

**Comment by jbremer** [comment] 2015-06-30 12:34
Could you maybe share your `.bson` files from the `log` directory? And also, is this bug reproducable? (That is, do you also get it when you do `./utils/process.py -r task_id` again?)

**Comment by SpoonBoy** [comment] 2015-06-30 13:28
Yes it is reproducible using the `./utils/process.py -r task_id`
the png is a 7z file, containing the whole analysis dir.
![analysis_1](https://cloud.githubusercontent.com/assets/6861971/8431822/509d1380-1f3c-11e5-82b3-6b77fc38d75d.png)

**Comment by nsmfoo** [comment] 2015-07-02 13:58
I can confirm this one as well: "ValueError: I/O operation on closed file". 

Closing the files before the reports is finished perhaps?

**Comment by jbremer** [comment] 2015-07-02 14:03
Weird - not much changed to the processing lately. In the `master` branch anyway. Will have to investigate later.

**Comment by nsmfoo** [comment] 2015-07-02 14:09
Tests on the master branch. Most likely not an error in process.py, diff between 1.2 and master is:
---
24c24
< from lib.cuckoo.core.startup import init_modules
---
> from lib.cuckoo.core.startup import init_modules, drop_privileges
127a128
>     parser.add_argument("-u", "--user", type=str, help="Drop user privileges to this user")
128a130,132
--

Just because, I tried with 1.2 process.py and got the same error.

So the Issue is somewhere else ..

**Comment by SpoonBoy** [comment] 2015-07-02 14:31
I have a **working** environment running with version 15d6bba6fb7977fe98f9e8c58bf1708fc304922b

looking at the commit timeline, the error come from c30b7a873a891

on latest mainstream, changing deepcopy to the dict version works.

**Comment by jbremer** [comment] 2015-07-02 14:34
Ah, makes sense.. the enumeration of `process["calls"]` involves seeking through a custom enumerator which reads from the *bson* file. Should probably revert the `copy.deepcopy()` thing for now.
Soon we're merging various big changes so then we can re-evaluate the deepcopy issue.

**Comment by jbremer** [comment] 2015-07-17 13:18
While merging the latest changes into the `master` branch @rep reverted the change that caused this issue (c30b7a873a891760d5d32d80f039f703056c3046). So closing this issue.
Have to check #590 though to see whether we have to make a different change now..

**Closed by jbremer** 2015-07-17 13:18 UTC
Labels: Bug (to verify)
