### ISSUE TITLE
Database error when updating tasks status

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#467] opened 2015-02-05 01:44 UTC
INFO:root:Processing analysis data for Task #111
ERROR:root:Exception when processing task ID 111.
Traceback (most recent call last):
  File "./process.py", line 59, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError
DEBUG:lib.cuckoo.core.database:Database error setting status: (DataError) (1265, "Data truncated for column 'status' at row 1") 'UPDATE tasks SET status=%s WHERE tasks.id = %s' ('failed_processing', 111L)
INFO:root:Processing analysis data for Task #111
ERROR:root:Exception when processing task ID 111.

Anyone encountered this kind of error?

**Comment by supahal** [comment] 2015-02-05 03:16
It falls under #Pending_results maintenance.

**Comment by supahal** [comment] 2015-02-05 03:24
1. Submit sample, process_result should be separate thread
2. process.py -dr -p 10 auto

once the analysis task is done.
2015-02-05 09:57:11,115 [lib.cuckoo.core.scheduler] DEBUG: Released database task #112 with status True
2015-02-05 09:57:11,115 [lib.cuckoo.core.scheduler] INFO: Task #112: analysis procedure completed

exception will occur on process.py

**Comment by jekil** [comment] 2015-02-05 20:29
Thanks of reporting.
I can't reproduce your bug so more information are needed (i.e. are you running latest master release, the issue happens for every task, do you tried to clean and delete the database).

**Comment by supahal** [comment] 2015-02-07 22:26
I running latest master release with --clean db feature.
Still producing the bug.

DEBUG:lib.cuckoo.core.database:Database error setting status: (DataError) (1265, "Data truncated for column 'status' at row 1") 'UPDATE tasks SET status=%s WHERE tasks.
id = %s' ('failed_processing', 1L)
INFO:root:Processing analysis data for Task #1
ERROR:root:Exception when processing task ID 1.
Traceback (most recent call last):
  File "./process.py", line 59, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError

**Comment by supahal** [comment] 2015-02-07 22:28
1. python cuckoo.py --clean
2. python cuckoo.py -d
3. python process.py -dr -p 10 auto

malware sha256=7b217450c2b15609025d09ade7580f38b20912d0b4f961eadb3dad3148feab5d

**Comment by supahal** [comment] 2015-02-07 22:40
upon checking the db, 
'UPDATE tasks SET status='failed_processing' WHERE tasks.id = 1'

but status type is  enum('pending','running','completed','reported','recovered')

**Comment by supahal** [comment] 2015-02-08 06:59
This is an update.
Already did setup latest cuckoo revision, with mysql connection and process_result=off

Still having problem on auto process.

INFO:root:Processing analysis data for Task #3
ERROR:root:Exception when processing task ID 3.
Traceback (most recent call last):
  File "./process.py", line 59, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:436: Warning: Data truncated for column 'status' at row 1
  cursor.execute(statement, parameters)

**Comment by jekil** [comment] 2015-02-08 23:58
Thanks, i will check tomorrow with the same setup.

**Comment by begosch** [comment] 2015-02-10 18:02
I am also having a similar issue.  Maybe it is related to the @classlock decorator?

2015-02-10 08:51:52,782 [lib.cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
INFO:root:Processing analysis data for Task #1
DEBUG:lib.cuckoo.core.database:Database error listing tasks: This result object does not return rows. It has been closed automatically.
WARNING:sqlalchemy.pool.QueuePool:Error closing cursor: (2014, "Commands out of sync; you can't run this command now")

**Comment by jekil** [comment] 2015-02-11 19:15
Guys, it doesn't happen to me, so i need some help to reproduce this. More details you give, better is. Which db? Does It happen random? Does it happen at the first analysis or the 1000nd? How many sample do you run to triggger it?

**Comment by supahal** [comment] 2015-02-12 01:51
Setup:
1. Latest master release of cuckoo
2. ./cuckoo.py --clean
3. Conf/cuckoo.py: process_result = off
4. Machine: ESX having 10 machines waiting for analysis task.
5. ./cuckoo.py -d and the other tab will ./process.py -drp 10 auto

Btw, im using mysql as my database.
mysql  Ver 14.14 Distrib 5.6.19, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by supahal** [comment] 2015-02-12 01:54
Does It happen random? 
- No. It happened to me by the time cuckoo finished the analysis.

Does it happen at the first analysis or the 1000nd? 
- Every analysis.

How many sample do you run to triggger it?
- I can duplicate it using any sample.

**Comment by XayOn** [comment] 2015-02-12 10:37
I probably can help a bit here, the problem is process.py is putting some analisys as "failed_processing"... a status wich is not correctly inserted into the ENUM in the database, here, have a look: https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/database.py#L273

=)

**Comment by jekil** [comment] 2015-02-12 23:09
Uhm it could be, I tested it with sqlite which is not enforcing enum as mysql

**Comment by jekil** [comment] 2015-02-15 16:01
@supahal Is it fixed now for you?

**Comment by rep** [comment] 2015-03-02 15:31
Should be fixed / solved with our commits related to the locking on Database().

Please re-open if the problem occurs again after 1.2 release.

**Closed by rep** 2015-03-02 15:31 UTC
Labels: Bug (to verify)
