### ISSUE TITLE
InvalidDocument: documents must have only string keys, key was 20011

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#458] opened 2015-02-03 05:52 UTC
2015-02-03 13:30:21,214 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/root/AL/cuckoo/lib/cuckoo/core/plugins.py", line 501, in process
    current.run(self.results)
  File "/root/AL/cuckoo/modules/reporting/mongodb.py", line 221, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 285, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 415, in insert
    self.uuid_subtype, client)
InvalidDocument: documents must have only string keys, key was 20011

**Comment by jekil** [comment] 2015-02-03 22:35
Thanks for reporting. Could you please provide more information? The sample or a test case we can use would be great.

**Comment by supahal** [comment] 2015-02-04 02:57
Basic test case:
1. Submit analysis
2. once the process is done, run cuckoo clean (python cuckoo.py --clean)
2. Run process.py -d -r {recent analysis}

This will duplicate the error.

**Comment by supahal** [comment] 2015-02-04 06:19
I encountered this error where processing:
SHA1: 59bce26cabe6f6a387a9b54b53a8b605ae162466

process_result should be off.

**Comment by jekil** [comment] 2015-02-06 22:36
I run the sample  with latest cuckoo from master and process_result=off a I did not get the error. So more investigation is needed from you. Can you please try with latest release and with clean DBs?

**Comment by rep** [comment] 2015-02-23 13:34
We don't have enough information - for example exact cuckoo version used.

This might have been a temporary glitch on master branch. I can't reproduce - it works absolutely fine on my current setup, regardless of process_results setting.

So closing this as invalid.

**Closed** 2015-02-23 13:34 UTC
Labels: Bug (to verify), Invalid, Rejected
