### ISSUE TITLE
alembic fail. Pymongo updated

### ISSUE THREAD

**Issue by m-messiah** [cuckoobox/cuckoo#614] opened 2015-08-14 06:01 UTC
In new pymongo there is no module connection, so alembic can not start and do its work.
It is needed to update alembic scripts or pin version of pymongo in requirements.txt.

**Comment by jbremer** [comment] 2015-08-14 15:07
The biggest issue here is the fact that two or three dependencies that we released in `requirements.txt` for Cuckoo 1.2 have now been updated to versions that are not backwards compatible (i.e., at least `pymongo` and `sqlalchemy`). That is, we used some functionality that is no longer supported.
For upcoming versions we should probably do the following:
* Pin versions of dependencies to the latest and greatest available at the time of release & tested.
* Release new minor versions when updates of important dependencies have been released.

If anyone has thoughts on this matter, please do let me know.

**Comment by jbremer** [comment] 2015-08-14 15:24
Closing this issue as duplicate of #602. We still have to do this, though ;)

**Closed by jbremer** 2015-08-14 15:24 UTC
