### ISSUE TITLE
Disable screenshots on configuration file

### ISSUE THREAD

**Issue by AndreC10002** [cuckoobox/cuckoo#323] opened 2014-05-08 15:00 UTC
This is a feature/enhancement request.

I'd like to suggest that screenshots can be disabled in the Cuckoo configuration file.  Currently, if you have the required software installed, the only way to stop Cuckoo from taking screenshots is by modifying the Python code.

At least for us, screenshots are not useful and consume extra time to load the UI and disk space.

Thank you!

**Comment by jbremer** [comment] 2015-05-10 14:15
This feature has been introduced as part of task `options`. See also the comments in #531.
Additionaly it would be nice to pass along configuration settings as well, so I'll keep this issue open, but for now there's at least some progress.

**Comment by jbremer** [comment] 2015-08-19 18:31
Closing this issue as a duplicate of the more recent #531.

**Closed by jbremer** 2015-08-19 18:31 UTC
Labels: Feature
