### ISSUE TITLE
Volatility 2.5 support

### ISSUE THREAD

**Issue by lehuff** [cuckoobox/cuckoo#675] opened 2015-11-03 19:37 UTC
Installed latest version of cuckoo from git and installed Volatility 2.5. Running cuckoo with memory processing turned on returns the following error:

ERROR: Cannot run volatility module: volatility library not available.

Verified through python interpreter that volatility can be imported.  Scan runs properly otherwise and returns appropriate results.

**Comment by jbremer** [comment] 2015-11-03 19:39
Thanks for reporting, we will check it out in a little bit. Probably we're important a now-deprecated function or so.
CC @botherder @jekil

**Comment by botherder** [comment] 2015-11-15 00:15
Volatility 2.5 works fine for me. There are just a couple of things that need to be fixed. Are you sure you installed it correctly?

**Comment by jbremer** [comment] 2015-11-22 00:56
Seems to work fine for me as well, btw.

**Comment by utkonos** [comment] 2015-11-26 10:53
The problem is fixed by installing the following:
sudo pip install pycrypto

The reason this is working for some of you is that you had installed this dependency when you installed volatility 2.4. Volatility 2.5 does not automatically install this dependency during its install process. I would expect that the OP has a new install and is therefore missing this dependency.

The line of code that is causing the problem is this one:
>>> import volatility.plugins.getsids
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/volatility-2.5-py2.7.egg/volatility/plugins/getsids.py", line 33, in <module>
    import volatility.plugins.registry.registryapi as registryapi
  File "/usr/local/lib/python2.7/site-packages/volatility-2.5-py2.7.egg/volatility/plugins/registry/registryapi.py", line 31, in <module>
    import volatility.win32.hashdump as hashdump
  File "/usr/local/lib/python2.7/site-packages/volatility-2.5-py2.7.egg/volatility/win32/hashdump.py", line 32, in <module>
    from Crypto.Hash import MD5, MD4
ImportError: No module named Crypto.Hash

This bug is not with Cuckoo, it is upstream so I think this can be marked closed

**Comment by ba277351771** [comment] 2015-12-16 08:06
when I run cuckoo with volatility 2.5 ,I got the error :

 2015-12-16 15:45:29,968 [volatility.debug] WARNING: NoneObject as string: Cannot find process session 

I don't what does it mean and how to solve it , I have reinstall volatility several times,but it doesn't work.

**Comment by jbremer** [comment] 2015-12-16 08:36
These come from the Volatility library and we haven't really pinpointed yet how to properly resolve it, so to be continued ;-)

**Comment by ba277351771** [comment] 2015-12-16 08:49
thank you very much

**Comment by botherder** [comment] 2015-12-23 13:01
Closing this ticket.

**Closed by botherder** 2015-12-23 13:01 UTC
