### ISSUE TITLE
KVM VM does not start

### ISSUE THREAD

**Issue by stevengoossensB** [cuckoobox/cuckoo#426] opened 2014-12-15 16:42 UTC
Hi,

I have a problem with the default libvirt implementation and the override ivm.py is doing. It seems that the method to restore the snapshot in the libvirt API does not automatically start the VM after restoring. This creates the issue that cuckoo is restoring the snapshot, but is not starting the VM. When I manually start the VM while Cuckoo is waiting for it, everything after that goes well.

I guess a kvm.py implementation would resolve this issue. Does anyone have one yet?

Rgds,

Steven

**Comment by voleg** [comment] 2015-01-15 10:00
+1

**Comment by voleg** [comment] 2015-01-15 14:15
temporary workaround:

```python
369             try:
370                 self.vms[label].revertToSnapshot(snapshot, flags=0)
371 
372                 # look for bug status plz..
373                 # https://github.com/cuckoobox/cuckoo/issues/426
374                 self.vms[label].create()
375 
376             except libvirt.libvirtError:
377                 raise CuckooMachineError("Unable to restore snapshot on "
378                                          "virtual machine {0}".format(label))
```

**Comment by jekil** [comment] 2015-01-25 21:36
Thanks for reporting, i am investigating on it.

**Comment by jekil** [comment] 2015-01-31 22:36
I run some tests with latest Xubuntu and i am unable to reproduce the bug. Can you please add more details? (OS, libvirt version, etc.)

**Comment by KillerInstinct** [comment] 2015-02-01 08:00
If I'm reading your issue correctly, it seems to have shut your VM down before taking the snapshot. The snapshot should be taken when the VM is On and the agent is listening, per the documentation.

**Comment by rep** [comment] 2015-02-23 13:47
Let me be the cleaner on this one. We can't reproduce and we don't have enough information anyways - this might have been a temporary glitch in the libvirt lib or our module for it - which has since been fixed.

Closing this, feel free to re-open if it happens again. With more details then, please :)

**Closed** 2015-02-23 13:47 UTC
Labels: Bug (to verify), Rejected

**Comment by bbb31** [comment] 2017-10-19 00:54
I want to confirm; this *is* an issue with Ubuntu Server 16.04. Cuckoo hangs on attempting to start the VM; giving the following error:

```
...
2017-10-18 20:52:45,710 [cuckoo.common.abstracts] DEBUG: Waiting 61 cuckooseconds for machine win7-cuckoo to switch to status ('running',)
2017-10-18 20:52:45,717 [cuckoo.core.scheduler] ERROR: Error starting Virtual Machine! VM: win7-cuckoo, error: Timeout hit while for machine win7-cuckoo to change status
```

Other info:

```
$ virsh -v
1.3.1

$ libvirtd -V
libvirtd (libvirt) 1.3.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by doomedraven** [comment] 2017-10-19 09:22
That isnt a issue, see my response in your pr
