### ISSUE TITLE
Errno 30 - Function not implemented in Database

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#622] opened 2015-08-18 09:48 UTC
```python
'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0x8ff70b115b10>>
```

**Comment by jbremer** [comment] 2015-08-18 10:02
Can you provide us with the sqlalchemy version you're using, which line this error occurs, etc etc?

**Comment by jbremer** [comment] 2015-09-03 12:45
Closing this issue as proper information is lacking (and this bug seems very unlikely to me).

**Closed by jbremer** 2015-09-03 12:45 UTC

**Comment by jbremer** [comment] 2015-09-07 08:29
Ran into the same issue by accident. Please paste the full stacktrace next time ;-)

**Comment by jhg** [comment] 2015-09-23 21:45
@jbremer I read it now, sorry, next time I paste full stacktrace :D

**Comment by srishti-agarwal** [comment] 2016-08-22 09:50
@jbremer 
I am running into the issue
Traceback (most recent call last):
  File "./cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 28, in <module>
    db = Database()
  File "/home/cuckoo/cuckoo/lib/cuckoo/common/utils.py", line 206, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/database.py", line 386, in __init__
    raise CuckooDatabaseError("Unable to create database directory: {0}".format(e))
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /home/cuckoo/cuckoo/db
Exception AttributeError: "'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0xb5bd6cac>> ignored

**Comment by ikennarene** [comment] 2016-11-22 12:57
rene@malware:~/cuckoo$ python cuckoo.py
Traceback (most recent call last):
  File "cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/home/rene/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/home/rene/cuckoo/lib/cuckoo/core/guest.py", line 28, in <module>
    db = Database()
  File "/home/rene/cuckoo/lib/cuckoo/common/utils.py", line 206, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/rene/cuckoo/lib/cuckoo/core/database.py", line 386, in __init__
    raise CuckooDatabaseError("Unable to create database directory: {0}".format(e))
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /home/rene/cuckoo/db
Exception AttributeError: "'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0x7fa637d0d210>> ignored                   


can i get help

**Comment by doomedraven** [comment] 2016-11-22 12:58
provide answers to second comment here plz

**Comment by jbremer** [comment] 2016-11-22 12:58
First of all, please upgrade to `2.0-rc2` as per http://cuckoosandbox.org/
Secondly, please fill out the configuration correctly - you're missing the `[database]` section in `cuckoo.conf`.

**Comment by ikennarene** [comment] 2016-11-24 14:08
@jbremer  thanks.
 
The next problem i face now. When i run python cuckoo.py, i get 
 [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.behavior": No module named dateutil.parser

**Comment by doomedraven** [comment] 2016-11-24 14:09
https://github.com/cuckoosandbox/cuckoo/blob/master/requirements.txt#L30
you have missed deps

**Comment by ikennarene** [comment] 2016-11-24 14:11
@doomedraven , can i get a guide , thanks

**Comment by doomedraven** [comment] 2016-11-24 14:13
read it -> http://docs.cuckoosandbox.org/en/latest/installation/host/requirements/

```
In order to properly function, Cuckoo requires some dependencies. They can all be installed through PyPI like this:

$ sudo pip install -r requirements.txt
```

**Comment by ikennarene** [comment] 2016-11-24 15:11
Could not find .egg-info directory in install record for Pillow==3.2.0 (from peepdf==0.3.2->-r requirements.txt (line 23))
  Running setup.py install for pythonaes
    
  Could not find .egg-info directory in install record for pythonaes==1.0 (from peepdf==0.3.2->-r requirements.txt (line 23))
Successfully installed Pillow pythonaes
Cleaning up...

**Comment by ikennarene** [comment] 2016-11-24 15:12
any idea on this  

Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

2016-11-25 11:11:15,422 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0-rc2
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Machine arch: x86_64

Traceback (most recent call last):
  File "cuckoo.py", line 122, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 93, in cuckoo_main
    sched.start()
  File "/home/rene/cuckoo/lib/cuckoo/core/scheduler.py", line 670, in start
    self.initialize()
  File "/home/rene/cuckoo/lib/cuckoo/core/scheduler.py", line 615, in initialize
    machinery.initialize(machinery_name)
  File "/home/rene/cuckoo/lib/cuckoo/common/abstracts.py", line 94, in initialize
    self._initialize(module_name)
  File "/home/rene/cuckoo/lib/cuckoo/common/abstracts.py", line 118, in _initialize
    machine.platform = machine_opts["platform"]
KeyError: 'platform'

**Comment by jbremer** [comment] 2016-11-24 15:19
@ikennarene You're missing the `platform` configuration value in your `virtualbox.conf`.

**Comment by ikennarene** [comment] 2016-11-25 09:56
@jbremer @doomedraven Thanks alot.  

This is my recent issue, after analysis and i click on Network Analysis , i get the below error. I have tried to install httpreplay, but still have the error.


Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks.

**Comment by doomedraven** [comment] 2016-11-25 10:17
is nto error, just warning, and that is solved in package branch, so just ignore it if you installed dependencies from requieremnt.txt

**Comment by ikennarene** [comment] 2016-11-25 16:26
thanks, but am not able to run PCAP file.
and i get this error under information on execution:  
Error: Machinery error: VBoxManage exited with error restoring the machine's snapshot

**Comment by doomedraven** [comment] 2016-11-25 17:38
What do you mean run pcap? Can you verify manusaly what you can restore snapshot and it in runned state and communication with vm works with curl vmip:8000 you should get error 50x

**Comment by ikennarene** [comment] 2016-11-25 20:16
pcap file. I have some malware file with pcap extension and all are in zip file, so when import it into cuckoo i get the warning (Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks.), thats why i want to know if there is a way to solve the warning.

Also, i want to enable malheur in my reporting.conf, i already enable = yes, but i still not getting result for malheur

**Comment by doomedraven** [comment] 2016-11-25 20:27
don't care about this, i told is solved in package and is not a bug and error, is just warning
`Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks.`

cuckoo v2 not support pcap analysis

**Comment by ikennarene** [comment] 2016-11-27 10:17
just started seeing this error after using cuckoo yesterday and working fine.

ERROR :-(
Error adding task to Cuckoo's database.
