### ISSUE TITLE
Inquiry: Do you encounter this issue when cuckoo runs tcpdump (having non-root user)?

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#501] opened 2015-03-18 01:49 UTC
tcpdump: eth0: You don't have permission to capture on that device

**Comment by gaelmuller** [comment] 2015-03-18 08:24
This is a normal error, and the current documentation should prevent against it:

https://cuckoo.readthedocs.org/en/latest/installation/host/requirements/#installing-tcpdump

It says that you should set specific capabilities on the binary:

```
$ sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

**Comment by jekil** [comment] 2015-03-18 23:36
As @gaelmuller said, it is not a bug but a point in the documentation you probably miss. I am closing this issue. Feel free to re-open it if you have more in-topic requests.

**Closed by jekil** 2015-03-18 23:36 UTC
Labels: Invalid, Rejected

**Comment by supahal** [comment] 2015-03-23 03:05
Shoot. Thank you for the help.
