### ISSUE TITLE
Volatility error

### ISSUE THREAD

**Issue by mmogilko** [cuckoobox/cuckoo#395] opened 2014-10-15 10:58 UTC
Hi all!
This  issue has been described before, but never described its concrete solution. All dependencies are installed, different versions of cuckoo and volatility (stable, development, from source and repo) are tried, but the problem persists.
Сockoo was deployed by this manual: https://translate.google.com.ua/translate?hl=ru&sl=ru&tl=en&u=http%3A%2F%2Fhabrahabr.ru%2Fpost%2F234467

OS: Ubuntu 14.04.1
Python-2.7.5; volatility 2.3.1 from repo

2014-10-14 12:44:43,010 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label Windows7 to path /opt/cuckoo/storage/analyses/3/memory.dmp
2014-10-14 12:44:56,205 [volatility.obj] WARNING: NoneObject as string: Cannot find process session
2014-10-14 12:44:56,207 [volatility.obj] WARNING: NoneObject as string: Cannot find process session
2014-10-14 12:44:56,267 [volatility.obj] WARNING: NoneObject as string: Pointer ObjectTable invalid
2014-10-14 12:44:56,269 [volatility.obj] WARNING: NoneObject as string: Pointer ObjectTable invalid
2014-10-14 12:44:56,272 [volatility.obj] WARNING: NoneObject as string: Pointer ObjectTable invalid
2014-10-14 12:46:37,845 [volatility.obj] WARNING: NoneObject as string: No path, service isn't running
2014-10-14 12:46:37,853 [volatility.obj] WARNING: NoneObject as string: No path, service isn't running
2014-10-14 12:46:37,860 [volatility.obj] WARNING: NoneObject as string: No path, service isn't running
2014-10-14 12:46:37,862 [volatility.obj] WARNING: NoneObject as string: No path, service isn't running
............

**Comment by jekil** [comment] 2015-01-25 21:52
Confirmed, thanks for reporting.

**Comment by jekil** [comment] 2015-01-25 22:01
It seems an error generated by volatility and not related to cuckoo https://github.com/volatilityfoundation/volatility/blob/c77f6854d3a03b21350569ef8e5af34048d71bd6/volatility/plugins/malware/svcscan.py#L123
Still investigating..

**Comment by rep** [comment] 2015-02-23 13:14
It's not a critical error - just a warning log message. Doesn't break our results / logging in any way and there's not much we can do about it on the Cuckoo side.

Check with volatility if you suspect it's an issue in their code (which I don't think it is) - otherwise disregard.

Closing as won't fix.

**Closed** 2015-02-23 13:14 UTC
Labels: Bug (confirmed), Invalid, Rejected

**Comment by JReming85** [comment] 2018-09-21 14:36
This is a very simple issue.

It is caused by volatility not being able to find certain things in memory due to windows putting that part into the paging file.

The simple fix for this is to either give your vm more ram, or turn of paging.

**Comment by soutzis** [comment] 2020-08-16 22:26
@JReming85 Thank you for clarifying
